# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180714_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogspost',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='update'),
        ),
    ]
