# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogspost_update_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogsPost',
            new_name='Article',
        ),
    ]
